config/routes.rb
Monblog::Application.routes.draw do
  get "/inscription" =>'users#new'
  get "/connexion" => 'sessions#new'
  get "/deconnexion" => 'sessions#destroy'
  get "comments/create"
  get "comments/destroy"
  get "comments/new"
  get "comments/show"
  resources :sujets do
    resources :comments
  end
  resources :comments
root 'sujets#index'
resources :users
resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :sujet
validates :commentaire, :presence => true , 
			:length=>{:minimum => 3 }
	

end

app/models/sujet.rb
class Sujet < ActiveRecord::Base
	has_many :comments 
	validates :titre , 
		:presence => true  , 
		:length   => { :maximum => 50 , :minimum => 2 }
	validates :contenu , 
			   :presence => true , 
			   :length => {:maximum => 200 , :minimum => 6}
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :destroy]
def set_comment
	@comment=Comment.find(params[:id])
	@sujet=@comment.sujet
end

def create
	
		#recuperer le sujet du commentaire 
	 @sujet=Sujet.find(params[:sujet_id])
	session[:titre]=@sujet.titre
	@comment=@sujet.comments.create(comment_params)
  
   respond_to do |format|
      if @comment.save
        format.html { redirect_to @sujet, notice: 'Commentaires cree avec succes' }
        format.json { render action: 'show', status: :created, location: @sujet }
      else
      	flash[:error] =@comment.errors.full_messages.join(',').gsub(','," et le ")
        format.html { redirect_to @sujet}
       # format.json { render json: @comment.errors, status: :unprocessable_entity }
      end

    end


end 
=begin

    respond_to do |format|
      if @sujet.save
        format.html { redirect_to @sujet, notice: t('succes_created') }
        format.json { render action: 'show', status: :created, location: @sujet }
      else
        format.html { render action: 'new' }
        format.json { render json: @sujet.errors, status: :unprocessable_entity }
      end

    end
=end 

 

  def destroy

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @sujet }
      format.json { head :no_content }
    end
end 
  def new
  end

  def show

  end

   def comment_params
   	 @param='test param'
   	  params.require(:comment).permit(:commentaire)
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper
  def new

  end

  def create
@user=User.where(login: params[:session][:login], passe: params[:session][:passe]) #retourn un tableau vide si rien
if ! @user.empty?
	@us=@user.first
	flash[:notice]= @us.login	
	connecter @us
	redirect_to sujets_path


else 
flash[:erreur]='Connexion erreur'
	redirect_to connexion_path
end 
  end

  def destroy
  	deconnecter 
  	redirect_to connexion_path
  end
def user_params
     
    end

end

app/controllers/sujets_controller.rb
class SujetsController < ApplicationController
  before_action :set_sujet, only: [:show, :edit, :update, :destroy]
  # GET /sujets
  # GET /sujets.json
  def index
    @sujets = Sujet.all

  end
  # GET /sujets/1
  # GET /sujets/1.json
  def show
    @titre =t('hello ') 

   
  end
  # GET /sujets/new
  def new
    @sujet = Sujet.new

  end
  # GET /sujets/1/edit
  def edit
  end

  # POST /sujets
  # POST /sujets.json
  def create
    @sujet = Sujet.new(sujet_params)
    respond_to do |format|
      if @sujet.save
        format.html { redirect_to @sujet, notice: t('succes_created') }
        format.json { render action: 'show', status: :created, location: @sujet }
      else
        format.html { render action: 'new' }
        format.json { render json: @sujet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sujets/1
  # PATCH/PUT /sujets/1.json
  def update
    respond_to do |format|
      if @sujet.update(sujet_params)
        format.html { redirect_to @sujet, notice: 'Sujet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sujet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sujets/1
  # DELETE /sujets/1.json
  def destroy
    @sujet.destroy
    respond_to do |format|
      format.html { redirect_to sujets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sujet
      @sujet = Sujet.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sujet_params
      params.require(:sujet).permit(:titre, :contenu)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
   @users = User.paginate(:page => params[:page], per_page: 2)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :login, :passe, :statut)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 @@current_user=nil
def connecter user
	session[:login]=user.login
	session[:statut]=user.statut
	cookies[:user]={value: user.id, exprires: 1.minutes.from_now }
@@current_user=User.find(user.id)
	
end


def current_user
	@@current_user
end
def est_connecter?
!@@current_user.nil? && session  
end

def deconnecter
	reset_session
cookies=nil
session=nil
@@current_user=nil

end
end

app/helpers/sujets_helper.rb
module SujetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for([@sujet, Comment.new]) do |f| %>
<p><%= f.label :commentaire %>: <%= f.text_area :commentaire , cols: 40, rows: 10, :placeholder => 'Entrer un commentaire...' %></p>
<p><%= f.submit 'Ajouter le commentaire '%></p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<h3><%= flash[:error] %></h3>
<p>Find me in app/views/comments/new.html.erb</p>
<p><%=@comment.errors.any? %></p>
<%=@comment.errors.full_messages.join(',')%>
<%= render 'comments/form'%>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_header.html.erb
<div style="background:red;color:white;height:30px;">
<% if est_connecter? %>
<div>Bienvenue <%= current_user.login %></div>
<%=link_to 'deconnecter' , deconnexion_path %>
<% else %>
<div>Non connecté </div>

<% end %>

</div>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mon blog</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Accueil</a></li>
            <li><%=link_to 'Sujets', sujets_path %></li>
            <li><%=link_to 'Connexion', connexion_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Top Sujets <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
               <% @su=Sujet.all %>
               <% @su.each do |u|%>
               <li><%=link_to u.titre , u %></li>
               <% end %>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div style="height:30px"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
</head>
<body>
<%= render 'layouts/header'%>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/sujets/_form.html.erb
<%= form_for(@sujet) do |f| %>
<div>
  <% if @sujet.errors.any? %>
  <%= pluralize(@sujet.errors.count,t('error')) %> 
  <ul>
  <% @sujet.errors.full_messages.each do |m| %>
<li><%= m %></li>
  </ul>
  <% end %>
  <% end %>

</div>
<div>
  <%=f.label :titre %>
  <%=f.text_field :titre %>
</div>
<div>
<%= f.label :contenu %>
<%= f.text_area :contenu %>
</div>
<div>
  <%= f.submit  'Valider'%>
</div>
<% end %>

app/views/sujets/edit.html.erb
<h1>Editing sujet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sujet %> |
<%= link_to 'Back', sujets_path %>

app/views/sujets/index.html.erb
<marquee><%=t('hello')%></marquee>
<p>Bienvenue <%= flash[:notice] %></p> 
<% if session[:login]

  %>
  <h4>Bienvenue  <%= session[:login]%> id est <%= cookies[:user]%> d'après le helper <%= current_user.login %></h4>
<% end %>
  
Titre session  <%=session[:titre]%>
<h1>Listes des sujets </h1>
<% @sujets.each do |s|%>
<p><%= link_to s.titre , s %></p>
<blockquote><%= truncate s.contenu %>(<%=link_to 'Modifier' , edit_sujet_path(s) %> |
 <%=link_to 'Supprimer', s,:method => :delete , :data => {:confirm =>  'vous etes sur de vouloir supprimer cet élément ?'} %> |)</blockquote>
<% end %>
<h3><%=link_to 'Nouveau sujet :', new_sujet_path %></h3>
<h3><%=link_to 'Listes des sujets ', sujets_path %></h3>

app/views/sujets/new.html.erb
<h1>Nouveau sujet</h1>

<%= render 'form' %>

<%= link_to t('back'), sujets_path %>

app/views/sujets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @sujet.titre %>
</p>

<p>
  <strong>Contenu:</strong>
  <%= @sujet.contenu %><br>
  <span>créé le : <%=time_ago_in_words @sujet.created_at %></span>
</p>

<%= link_to 'Modifier', edit_sujet_path(@sujet) %> |
<%= link_to 'Retour aux sujets', sujets_path %>
<%=link_to 'Supprimer',@sujet,:method => :delete , :data => {:confirm => 'Vous etes sur de vouloir supprimer cet élément? '}%>
<h3>Les commentaires: </h3>

il y a <%= pluralize(@sujet.comments.count,'commentaire')%>
<h3><%= flash[:error] %></h3>
<% @sujet.comments.each do |m|  %>


<p><%= m.commentaire %> | <%= time_ago_in_words m.created_at%> | <%=link_to 'Supprimer', m  ,:method => :delete ,:data => {:confirm => 'supprimer ?'}  %></p>
<% end %>

<h3>Ajouter les commentaires : </h3>

<%= render 'comments/form'%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :passe %><br>
    <%= f.password_field :passe %>
  </div>
  <div class="field">
    <%= f.label :statut  %><br>
   <%= f.label 'Admin'  %> <%= f.radio_button :statut , 'admin' %>
       <%= f.label 'Enregistré'  %>   <%= f.radio_button :statut , 'enregistré' %>
           
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Login</th>
      <th>Passe</th>
      <th>Statut</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.login %></td>
        <td><%= user.passe %></td>
        <td><%= user.statut %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<hr>
<h1>Liste des utilisateurs</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
     
      <%= link_to user.login, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate @users, :previous_label => 'Précédent', :next_label => 'Suivant' %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Passe:</strong>
  <%= @user.passe.gsub(/[a-z0-9]/,'*') %>
</p>

<p>
  <strong>Statut:</strong>
  <%= @user.statut %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>